version: "3.8"

services:
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
      - VITE_ML_BASE_URL=http://localhost:8000
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://dbs_miku21_capstone:82ThKGKmDzBhgNs8@luminouskin.qpczpnq.mongodb.net/?retryWrites=true&w=majority&appName=Luminouskin
      - JWT_SECRET=fajarudin

  ai_service:
    build: ./AI-image-detection
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload


volumes:
  mongo-data:
